[versions]
spigot = "1.21.8-R0.1-SNAPSHOT"
papermc = "1.21.8-R0.1-SNAPSHOT"
authlib = "1.5.21"
brigadier = "1.3.10"
kotlin-coroutines = "1.10.2"

[libraries]
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
papermc = { module = "io.papermc.paper:paper-api", version.ref = "papermc" }
authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }